export default TYPES = {
    INCREMENT_LIMIT: "INCREMENT_LIMIT",
    RESET_LIMIT: "RESET_LIMIT",
    USER_FETCH_REQUESTED: "USER_FETCH_REQUESTED",
    USER_FETCH_SUCCEEDED: "USER_FETCH_SUCCEEDED",
    USER_FETCH_FAILED: "USER_FETCH_FAILED"
}